### ISSUE TITLE
Suggestion: Add for a one-time only timer

### ISSUE THREAD

**Issue by ArvinB** [rnapier/RNTimer#1]
``` objective-c
RNTimer *timer = [[self alloc] init];
    timer.timerBlock = block;
    timer.source = dispatch_source_create( DISPATCH_SOURCE_TYPE_TIMER,
                                          0, 0,
                                          dispatch_get_main_queue() );

    uint64_t time = (uint64_t)(interval * NSEC_PER_SEC);
    dispatch_source_set_timer( timer.source,
                               dispatch_time(DISPATCH_TIME_NOW, time),
                               DISPATCH_TIME_FOREVER, 0 );
    dispatch_source_set_event_handler( timer.source, ^{

        [timer fire];
        [timer invalidate];
    });

    dispatch_resume( timer.source );
    return timer;
```

**Comment by rnapier** [comment]
Can you discuss how this is better than just using dispatch_after() or a simple non-repeating NSTimer?

**Comment by ArvinB** [comment]
I am learning gcd, so yeah dispatch after is better. Using nastier requires
run loop. I like gcd better.

From:  Rob Napier notifications@github.com
Reply-To:  rnapier/RNTimer
<reply+i-6856098-b831d8d72ed79617a2e81680906e6c63a66675cd-1202744@reply.gith
ub.com>
Date:  Thursday, September 13, 2012 3:23 PM
To:  rnapier/RNTimer RNTimer@noreply.github.com
Cc:  Arvin Bhatnagar arvinb@columbus.rr.com
Subject:  Re: [RNTimer] Suggestion: Add for a one-time only timer (#1)

Can you discuss how this is better than just using dispatch_after() or a
simple non-repeating NSTimer?

 ‹
 Reply to this email directly or view it on GitHub
https://github.com/rnapier/RNTimer/issues/1#issuecomment-8539906 .

**Comment by ArvinB** [comment]
For completeness dispatch_after() does work well 

```
+ (void) scheduletimerWithInterval:(NSTimeInterval)interval block:(dispatch_block_t)block {

    dispatch_after( dispatch_time(DISPATCH_TIME_NOW, interval * NSEC_PER_SEC), dispatch_get_main_queue(), block );
}
```

So just a recommendation to add it for completeness. Nice stuff otherwise, I have re-purposed and am using (kudos).

**Comment by sunny131984** [comment]
HI guyz,
First of all thanks for your contribution on Git. It really help to lots of people.
I need to call some method on every day at specific time. I tried UIlocalnotification and it works seems fine but it notify the user that i don't want and i try to schedule timer with NStimer but it consumes lots of bettery so i don't want to use it. I need to run this activity in background and if application is restart than at that time it not affect to my call e.g i schedule time on every day on 9 AM ok. On first start i set some timer and i play with app for hour and after that i kill my app and start again on same dat at 7 PM than at that time not execute and if my app is in background for upto next day 9 AM than it execute method and fire some notification... please help to handle this

**Comment by rnapier** [comment]
@sunny131984 This question doesn't seem to be related to this issue, but I'm having some trouble understanding the question.

There is no general way to run a method at a specific time if you are not in the foreground. iOS breaks that on purpose; they don't want you to do it because it's bad for battery. The closest thing available is silent push notifications, but the user must be connected to the network, and you can't set them for a specific time.

You haven't explained the problem you're solving. If the user wants to interact at 9am, then an alert is the preferred solution. If the user doesn't want to interact at 9am, then there is no way for you to demand system resources at that time. What you can do is use Background App Refresh to coordinate being waken when the system believes the user might want something from you (so if the user accesses you at 9am every day, the system might wake you up a few minutes before that so you can get ready).

In any case, RNTimer is no different here than NSTimer. NSTimer does not use significant system resources (almost nothing), so I don't understand what you mean by "consumes lots of battery."

**Comment by sunny131984** [comment]
@rnapier  Thanks for your reply. I have sent mail on your id please respond on it
